version: "3.5"
services:
  timecapsule:
    build: .
    image: "timecapsule.timecapsule.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
    environment:
      - TM_USERNAME
      - TM_GROUPNAME=timemachine
      - PASSWORD
      - TM_UID=1000
      - TM_GID=1000
      - SET_PERMISSIONS=false
      - VOLUME_SIZE_LIMIT=512 GB
    volumes:
      - "timemachine:/opt/timemachine"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
volumes:
  timemachine: {}
